# -*- coding: utf-8 -*-
"""CrisisText_NLP_MiniProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lzG0-3BffnTWxVYfc0AXCqfZcb6FdHI6

# CrisisText: NLP-Based Humanitarian Information Classification for Disaster Response

## Mini NLP Project

### Objective
The objective of this project is to develop an NLP-based text classification system that automatically categorizes disaster-related social media messages into humanitarian information categories.
"""

import zipfile
import os

zip_path = "/content/crisismmd_datasplit_all.zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("/content/")

print("Dataset extracted successfully!")

import os

dataset_path = "/content/crisismmd_datasplit_all"

print(os.listdir(dataset_path))

import pandas as pd
import os

# Path to the extracted dataset
dataset_path = "/content/crisismmd_datasplit_all"

# File paths
train_file = os.path.join(
    dataset_path,
    "task_humanitarian_text_img_train.tsv"
)

dev_file = os.path.join(
    dataset_path,
    "task_humanitarian_text_img_dev.tsv"
)

test_file = os.path.join(
    dataset_path,
    "task_humanitarian_text_img_test.tsv"
)

# Load the TSV files
train_df = pd.read_csv(train_file, sep="\t")
dev_df = pd.read_csv(dev_file, sep="\t")
test_df = pd.read_csv(test_file, sep="\t")

print("Training data shape:", train_df.shape)
print("Development data shape:", dev_df.shape)
print("Testing data shape:", test_df.shape)

print("Columns in the dataset:")
print(train_df.columns.tolist())

pd.set_option("display.max_colwidth", 200)

train_df[["tweet_text", "label_text"]].head(10)

# Check missing values in the important columns

print("Missing values in tweet_text:")
print(train_df["tweet_text"].isnull().sum())

print("\nMissing values in label_text:")
print(train_df["label_text"].isnull().sum())

# Count how many tweets belong to each category

print(train_df["label_text"].value_counts())

import matplotlib.pyplot as plt

train_df["label_text"].value_counts().plot(kind="bar")

plt.title("Distribution of Humanitarian Categories")
plt.xlabel("Category")
plt.ylabel("Number of Tweets")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

print("Number of categories:", train_df["label_text"].nunique())

print("\nCategories:")
for category in train_df["label_text"].unique():
    print("-", category)

# Create a copy of the training, development and test datasets

train = train_df.copy()
dev = dev_df.copy()
test = test_df.copy()


# Function to merge the original CrisisMMD categories
# into the five categories recommended by the dataset authors

def merge_categories(label):
    if label in ["affected_individuals",
                 "injured_or_dead_people",
                 "missing_or_found_people"]:
        return "affected_individuals"

    elif label in ["infrastructure_and_utility_damage",
                   "vehicle_damage"]:
        return "infrastructure_and_utility_damage"

    elif label == "rescue_volunteering_or_donation_effort":
        return "rescue_volunteering_or_donation_effort"

    elif label == "other_relevant_information":
        return "other_relevant_information"

    elif label == "not_humanitarian":
        return "not_humanitarian"

    else:
        return label


# Apply the category mapping
train["category"] = train["label_text"].apply(merge_categories)
dev["category"] = dev["label_text"].apply(merge_categories)
test["category"] = test["label_text"].apply(merge_categories)


# Display the new categories
print("Categories after merging:\n")

print(train["category"].value_counts())

print("Number of categories:", train["category"].nunique())

print("\nFinal categories:")
for category in sorted(train["category"].unique()):
    print("-", category)

import re

# Function to fix common text encoding problems
def fix_encoding(text):
    try:
        return text.encode("latin1").decode("utf8")
    except (UnicodeEncodeError, UnicodeDecodeError):
        return text


# Function to clean tweet text
def clean_text(text):
    text = str(text)

    # Fix encoding problems
    text = fix_encoding(text)

    # Convert to lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r"http\S+|www\S+", "", text)

    # Remove retweet symbol
    text = re.sub(r"\brt\b", "", text)

    # Remove @mentions
    text = re.sub(r"@\w+", "", text)

    # Remove # symbol but keep the hashtag word
    text = re.sub(r"#", "", text)

    # Remove punctuation and special characters
    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text


# Apply cleaning to all three datasets
train["clean_text"] = train["tweet_text"].apply(clean_text)
dev["clean_text"] = dev["tweet_text"].apply(clean_text)
test["clean_text"] = test["tweet_text"].apply(clean_text)

print("Text preprocessing completed successfully!")

print("BEFORE CLEANING:")
print(train["tweet_text"].iloc[0])

print("\nAFTER CLEANING:")
print(train["clean_text"].iloc[0])

print("Before removing duplicates:")
print("Train:", len(train))
print("Dev:", len(dev))
print("Test:", len(test))

train = train.drop_duplicates(subset=["tweet_id"]).copy()
dev = dev.drop_duplicates(subset=["tweet_id"]).copy()
test = test.drop_duplicates(subset=["tweet_id"]).copy()

print("\nAfter removing duplicates:")
print("Train:", len(train))
print("Dev:", len(dev))
print("Test:", len(test))

print("Final training class distribution:\n")
print(train["category"].value_counts())

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))

train["category"].value_counts().plot(kind="bar")

plt.title("Distribution of Humanitarian Categories")
plt.xlabel("Category")
plt.ylabel("Number of Tweets")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()

plt.show()

from sklearn.feature_extraction.text import TfidfVectorizer

# Create TF-IDF vectorizer
tfidf = TfidfVectorizer(
    stop_words="english",
    max_features=10000,
    ngram_range=(1, 2),
    min_df=2
)

print("TF-IDF vectorizer created successfully!")

# Learn vocabulary from training data
X_train = tfidf.fit_transform(train["clean_text"])

# Transform development and test data
X_dev = tfidf.transform(dev["clean_text"])
X_test = tfidf.transform(test["clean_text"])

print("TF-IDF conversion completed!")
print("Training shape:", X_train.shape)
print("Development shape:", X_dev.shape)
print("Testing shape:", X_test.shape)

y_train = train["category"]
y_dev = dev["category"]
y_test = test["category"]

print("Target labels prepared successfully!")

print("\nTraining labels:")
print(y_train.value_counts())

from sklearn.naive_bayes import MultinomialNB

# Create the Naive Bayes model
nb_model = MultinomialNB()

# Train the model
nb_model.fit(X_train, y_train)

print("Naive Bayes model trained successfully!")

from sklearn.metrics import accuracy_score, classification_report

# Make predictions on development data
nb_dev_pred = nb_model.predict(X_dev)

# Calculate accuracy
nb_dev_accuracy = accuracy_score(y_dev, nb_dev_pred)

print("Naive Bayes Development Accuracy:",
      round(nb_dev_accuracy * 100, 2), "%")

print("\nClassification Report:")
print(classification_report(y_dev, nb_dev_pred))

from sklearn.linear_model import LogisticRegression

# Create Logistic Regression model
lr_model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced"
)

# Train the model
lr_model.fit(X_train, y_train)

print("Logistic Regression model trained successfully!")

# Make predictions on development data
lr_dev_pred = lr_model.predict(X_dev)

# Calculate accuracy
lr_dev_accuracy = accuracy_score(y_dev, lr_dev_pred)

print("Logistic Regression Development Accuracy:",
      round(lr_dev_accuracy * 100, 2), "%")

print("\nClassification Report:")
print(classification_report(y_dev, lr_dev_pred))

print("MODEL COMPARISON")
print("-----------------------------")

print("Naive Bayes Accuracy:",
      round(nb_dev_accuracy * 100, 2), "%")

print("Logistic Regression Accuracy:",
      round(lr_dev_accuracy * 100, 2), "%")

from scipy.sparse import vstack

# Combine training and development features
X_train_final = vstack([X_train, X_dev])
y_train_final = pd.concat([y_train, y_dev])

print("Final training data shape:", X_train_final.shape)
print("Final training labels:", len(y_train_final))

final_model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced"
)

final_model.fit(X_train_final, y_train_final)

print("Final Logistic Regression model trained successfully!")

from sklearn.metrics import accuracy_score, classification_report

# Predict the unseen test data
test_pred = final_model.predict(X_test)

# Calculate final test accuracy
test_accuracy = accuracy_score(y_test, test_pred)

print("FINAL TEST ACCURACY:",
      round(test_accuracy * 100, 2), "%")

print("\nFINAL CLASSIFICATION REPORT:")
print(classification_report(y_test, test_pred))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Create confusion matrix
cm = confusion_matrix(
    y_test,
    test_pred,
    labels=final_model.classes_
)

# Display confusion matrix
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=final_model.classes_
)

fig, ax = plt.subplots(figsize=(10, 8))

disp.plot(
    ax=ax,
    xticks_rotation=45
)

plt.title("Confusion Matrix - CrisisText")
plt.tight_layout()
plt.show()

from sklearn.metrics import precision_recall_fscore_support

# Calculate weighted and macro metrics
precision, recall, f1, _ = precision_recall_fscore_support(
    y_test,
    test_pred,
    average="weighted"
)

macro_precision, macro_recall, macro_f1, _ = precision_recall_fscore_support(
    y_test,
    test_pred,
    average="macro"
)

print("FINAL MODEL: Logistic Regression")
print("--------------------------------")
print("Accuracy :", round(test_accuracy * 100, 2), "%")
print("Precision:", round(precision, 3))
print("Recall   :", round(recall, 3))
print("F1-Score :", round(f1, 3))

print("\nMacro Average")
print("-------------")
print("Precision:", round(macro_precision, 3))
print("Recall   :", round(macro_recall, 3))
print("F1-Score :", round(macro_f1, 3))

# Example new disaster-related tweets

new_tweets = [
    "Many families have lost their homes after the hurricane.",
    "Volunteers are collecting food and donations for flood victims.",
    "The earthquake damaged roads and several buildings.",
    "Authorities shared information about the ongoing wildfire.",
    "I watched a video about the storm on social media."
]

# Clean the new tweets
clean_new_tweets = [clean_text(tweet) for tweet in new_tweets]

# Convert them using the SAME TF-IDF vectorizer
new_tfidf = tfidf.transform(clean_new_tweets)

# Predict categories
predictions = final_model.predict(new_tfidf)

# Display results
for tweet, prediction in zip(new_tweets, predictions):
    print("Tweet:", tweet)
    print("Predicted category:", prediction)
    print("-" * 80)

"""# Project Summary

The CrisisText project uses Natural Language Processing and machine learning to classify disaster-related social media messages into humanitarian information categories.

The system performs the following steps:

1. Loads the CrisisMMD dataset.
2. Explores and analyzes the dataset.
3. Cleans the textual data.
4. Merges related humanitarian categories.
5. Converts text into numerical TF-IDF features.
6. Trains Naive Bayes and Logistic Regression models.
7. Compares model performance.
8. Selects Logistic Regression as the final model.
9. Evaluates the final model using accuracy, precision, recall and F1-score.
10. Generates a confusion matrix.
11. Predicts categories for new disaster-related messages.

The project demonstrates how NLP can be used to organize large amounts of disaster-related textual information and potentially support humanitarian information analysis.
"""